### ISSUE TITLE
Create template from existing files: Blank browse dialog.

### ISSUE THREAD

**Issue by gbobr** [devryan/GamePanelX-V3#115]
In a fresh gpx install,
When creating a template from an existing folder, the "browse" button pops up a blank dialog, even when a server is selected.

I did a little digging and found that the ajax request is sending:

http://my.gpx.com/ajax/ajax.php?a=file_load_dir&browsetpl=1&reset=1&id=undefined

Instead of:

http://my.gpx.com/ajax/ajax.php?a=file_load_dir&browsetpl=1&reset=1&id=1

**Comment by devryan** [comment]
If you refresh the page a couple times, does the problem fix itself?  Sounds like a conflicting javascript variable that needs to be fixed

**Comment by devryan** [comment]
Ok @gbobr - This should be fixed.  Fixed a bug as well as added an error message that is more specific.  Since if it could not login to your remote server, it would just show a blank page.  Now it will show you the actual error.  https://github.com/devryan/GamePanelX-V3/commit/475955965f6d6181512e8ec937acac536b3a47f6

**Comment by devryan** [comment]
Sorry, this fix https://github.com/devryan/GamePanelX-V3/commit/39feefe2436a769a09fecb4a6c64c65409dad020 is the actual completed fix :+1:
